/*
 * Licence API
 *
 * API per la gestione delle licenze del client. Espone attivazione, rilascio di una nuova licenza e verifica dello stato corrente.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ActivateLicenceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivateLicenceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActivateLicenceRequest
        //private ActivateLicenceRequest instance;

        public ActivateLicenceRequestTests()
        {
            // TODO uncomment below to create an instance of ActivateLicenceRequest
            //instance = new ActivateLicenceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivateLicenceRequest
        /// </summary>
        [Fact]
        public void ActivateLicenceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActivateLicenceRequest
            //Assert.IsType<ActivateLicenceRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'NumeroCommessa'
        /// </summary>
        [Fact]
        public void NumeroCommessaTest()
        {
            // TODO unit test for the property 'NumeroCommessa'
        }
    }
}
