/*
 * Licence API
 *
 * API per la gestione delle licenze del client. Espone attivazione, rilascio di una nuova licenza e verifica dello stato corrente.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetNewLicenceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetNewLicenceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetNewLicenceRequest
        //private GetNewLicenceRequest instance;

        public GetNewLicenceRequestTests()
        {
            // TODO uncomment below to create an instance of GetNewLicenceRequest
            //instance = new GetNewLicenceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetNewLicenceRequest
        /// </summary>
        [Fact]
        public void GetNewLicenceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetNewLicenceRequest
            //Assert.IsType<GetNewLicenceRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'PreviousLicenceId'
        /// </summary>
        [Fact]
        public void PreviousLicenceIdTest()
        {
            // TODO unit test for the property 'PreviousLicenceId'
        }
    }
}
