/*
 * Licence API
 *
 * API per la gestione delle licenze del client. Espone attivazione, rilascio di una nuova licenza e verifica dello stato corrente.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Licenza
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LicenzaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Licenza
        //private Licenza instance;

        public LicenzaTests()
        {
            // TODO uncomment below to create an instance of Licenza
            //instance = new Licenza();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Licenza
        /// </summary>
        [Fact]
        public void LicenzaInstanceTest()
        {
            // TODO uncomment below to test "IsType" Licenza
            //Assert.IsType<Licenza>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Scadenza'
        /// </summary>
        [Fact]
        public void ScadenzaTest()
        {
            // TODO unit test for the property 'Scadenza'
        }

        /// <summary>
        /// Test the property 'Pagato'
        /// </summary>
        [Fact]
        public void PagatoTest()
        {
            // TODO unit test for the property 'Pagato'
        }
    }
}
