// <auto-generated>
/*
 * Licence API
 *
 * API per la gestione delle licenze del client. Espone attivazione, rilascio di una nuova licenza e verifica dello stato corrente.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ILicenceApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        LicenceApiEvents Events { get; }

        /// <summary>
        /// Attiva la licenza del cliente alla prima comunicazione col server
        /// </summary>
        /// <remarks>
        /// Invocata la prima volta che il client comunica col server. Genera una nuova licenza associata al cliente, con identificativo alfanumerico composto da numero commessa (LDK) + data/ora di attivazione + id cliente, e scadenza calcolata dal server.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="activateLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IActivateLicenceApiResponse"/>&gt;</returns>
        Task<IActivateLicenceApiResponse> ActivateLicenceAsync(ActivateLicenceRequest activateLicenceRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Attiva la licenza del cliente alla prima comunicazione col server
        /// </summary>
        /// <remarks>
        /// Invocata la prima volta che il client comunica col server. Genera una nuova licenza associata al cliente, con identificativo alfanumerico composto da numero commessa (LDK) + data/ora di attivazione + id cliente, e scadenza calcolata dal server.
        /// </remarks>
        /// <param name="activateLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IActivateLicenceApiResponse"/>?&gt;</returns>
        Task<IActivateLicenceApiResponse?> ActivateLicenceOrDefaultAsync(ActivateLicenceRequest activateLicenceRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Verifica lo stato corrente di una licenza
        /// </summary>
        /// <remarks>
        /// Restituisce lo stato della licenza identificata da licenceId: validita&#39;, data di scadenza, flag di pagamento. Puo&#39; essere usata anche come heartbeat del client (monitoraggio ogni 5 minuti).
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="licenceId">Identificativo alfanumerico della licenza</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICheckLicenceStateApiResponse"/>&gt;</returns>
        Task<ICheckLicenceStateApiResponse> CheckLicenceStateAsync(string licenceId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Verifica lo stato corrente di una licenza
        /// </summary>
        /// <remarks>
        /// Restituisce lo stato della licenza identificata da licenceId: validita&#39;, data di scadenza, flag di pagamento. Puo&#39; essere usata anche come heartbeat del client (monitoraggio ogni 5 minuti).
        /// </remarks>
        /// <param name="licenceId">Identificativo alfanumerico della licenza</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICheckLicenceStateApiResponse"/>?&gt;</returns>
        Task<ICheckLicenceStateApiResponse?> CheckLicenceStateOrDefaultAsync(string licenceId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Rilascia una nuova licenza al cliente come file da scaricare
        /// </summary>
        /// <remarks>
        /// Invocata dal client per ottenere una nuova licenza (p.es. dopo scadenza e pagamento avvenuto). Il server genera il file di licenza in locale e lo restituisce al client come download binario. I metadati della licenza (id, scadenza, pagato) vengono propagati tramite response header, mentre il body contiene il file stesso.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="getNewLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetNewLicenceApiResponse"/>&gt;</returns>
        Task<IGetNewLicenceApiResponse> GetNewLicenceAsync(GetNewLicenceRequest getNewLicenceRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Rilascia una nuova licenza al cliente come file da scaricare
        /// </summary>
        /// <remarks>
        /// Invocata dal client per ottenere una nuova licenza (p.es. dopo scadenza e pagamento avvenuto). Il server genera il file di licenza in locale e lo restituisce al client come download binario. I metadati della licenza (id, scadenza, pagato) vengono propagati tramite response header, mentre il body contiene il file stesso.
        /// </remarks>
        /// <param name="getNewLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetNewLicenceApiResponse"/>?&gt;</returns>
        Task<IGetNewLicenceApiResponse?> GetNewLicenceOrDefaultAsync(GetNewLicenceRequest getNewLicenceRequest, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IActivateLicenceApiResponse"/>
    /// </summary>
    public interface IActivateLicenceApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.Licenza?>, IBadRequest<Org.OpenAPITools.Model.ErrorResponse?>, INotFound<Org.OpenAPITools.Model.ErrorResponse?>, IConflict<Org.OpenAPITools.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 409 Conflict
        /// </summary>
        /// <returns></returns>
        bool IsConflict { get; }
    }

    /// <summary>
    /// The <see cref="ICheckLicenceStateApiResponse"/>
    /// </summary>
    public interface ICheckLicenceStateApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.LicenceStateResponse?>, INotFound<Org.OpenAPITools.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// The <see cref="IGetNewLicenceApiResponse"/>
    /// </summary>
    public interface IGetNewLicenceApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<System.IO.Stream?>, IBadRequest<Org.OpenAPITools.Model.ErrorResponse?>, IPaymentRequired<Org.OpenAPITools.Model.ErrorResponse?>, INotFound<Org.OpenAPITools.Model.ErrorResponse?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 402 PaymentRequired
        /// </summary>
        /// <returns></returns>
        bool IsPaymentRequired { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class LicenceApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnActivateLicence;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorActivateLicence;

        internal void ExecuteOnActivateLicence(LicenceApi.ActivateLicenceApiResponse apiResponse)
        {
            OnActivateLicence?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorActivateLicence(Exception exception)
        {
            OnErrorActivateLicence?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCheckLicenceState;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCheckLicenceState;

        internal void ExecuteOnCheckLicenceState(LicenceApi.CheckLicenceStateApiResponse apiResponse)
        {
            OnCheckLicenceState?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCheckLicenceState(Exception exception)
        {
            OnErrorCheckLicenceState?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetNewLicence;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetNewLicence;

        internal void ExecuteOnGetNewLicence(LicenceApi.GetNewLicenceApiResponse apiResponse)
        {
            OnGetNewLicence?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetNewLicence(Exception exception)
        {
            OnErrorGetNewLicence?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class LicenceApi : ILicenceApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<LicenceApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public LicenceApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LicenceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LicenceApi(ILogger<LicenceApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, LicenceApiEvents licenceApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<LicenceApi>();
            HttpClient = httpClient;
            Events = licenceApiEvents;
        }

        partial void FormatActivateLicence(ActivateLicenceRequest activateLicenceRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="activateLicenceRequest"></param>
        /// <returns></returns>
        private void ValidateActivateLicence(ActivateLicenceRequest activateLicenceRequest)
        {
            if (activateLicenceRequest == null)
                throw new ArgumentNullException(nameof(activateLicenceRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="activateLicenceRequest"></param>
        private void AfterActivateLicenceDefaultImplementation(IActivateLicenceApiResponse apiResponseLocalVar, ActivateLicenceRequest activateLicenceRequest)
        {
            bool suppressDefaultLog = false;
            AfterActivateLicence(ref suppressDefaultLog, apiResponseLocalVar, activateLicenceRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="activateLicenceRequest"></param>
        partial void AfterActivateLicence(ref bool suppressDefaultLog, IActivateLicenceApiResponse apiResponseLocalVar, ActivateLicenceRequest activateLicenceRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="activateLicenceRequest"></param>
        private void OnErrorActivateLicenceDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, ActivateLicenceRequest activateLicenceRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorActivateLicence(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, activateLicenceRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="activateLicenceRequest"></param>
        partial void OnErrorActivateLicence(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, ActivateLicenceRequest activateLicenceRequest);

        /// <summary>
        /// Attiva la licenza del cliente alla prima comunicazione col server Invocata la prima volta che il client comunica col server. Genera una nuova licenza associata al cliente, con identificativo alfanumerico composto da numero commessa (LDK) + data/ora di attivazione + id cliente, e scadenza calcolata dal server.
        /// </summary>
        /// <param name="activateLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IActivateLicenceApiResponse"/>&gt;</returns>
        public async Task<IActivateLicenceApiResponse?> ActivateLicenceOrDefaultAsync(ActivateLicenceRequest activateLicenceRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ActivateLicenceAsync(activateLicenceRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Attiva la licenza del cliente alla prima comunicazione col server Invocata la prima volta che il client comunica col server. Genera una nuova licenza associata al cliente, con identificativo alfanumerico composto da numero commessa (LDK) + data/ora di attivazione + id cliente, e scadenza calcolata dal server.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="activateLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IActivateLicenceApiResponse"/>&gt;</returns>
        public async Task<IActivateLicenceApiResponse> ActivateLicenceAsync(ActivateLicenceRequest activateLicenceRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateActivateLicence(activateLicenceRequest);

                FormatActivateLicence(activateLicenceRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/licence/activate"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/licence/activate");

                    httpRequestMessageLocalVar.Content = (activateLicenceRequest as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(activateLicenceRequest, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<ActivateLicenceApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ActivateLicenceApiResponse>();
                        ActivateLicenceApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/licence/activate", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterActivateLicenceDefaultImplementation(apiResponseLocalVar, activateLicenceRequest);

                        Events.ExecuteOnActivateLicence(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorActivateLicenceDefaultImplementation(e, "/api/licence/activate", uriBuilderLocalVar.Path, activateLicenceRequest);
                Events.ExecuteOnErrorActivateLicence(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ActivateLicenceApiResponse"/>
        /// </summary>
        public partial class ActivateLicenceApiResponse : Org.OpenAPITools.Client.ApiResponse, IActivateLicenceApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ActivateLicenceApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ActivateLicenceApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ActivateLicenceApiResponse(ILogger<ActivateLicenceApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="ActivateLicenceApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ActivateLicenceApiResponse(ILogger<ActivateLicenceApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.Licenza? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.Licenza>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.Licenza? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.ErrorResponse? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out Org.OpenAPITools.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.ErrorResponse? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out Org.OpenAPITools.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public bool IsConflict => 409 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 409 Conflict
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.ErrorResponse? Conflict()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsConflict
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 409 Conflict and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryConflict([NotNullWhen(true)]out Org.OpenAPITools.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = Conflict();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)409);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatCheckLicenceState(ref string licenceId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="licenceId"></param>
        /// <returns></returns>
        private void ValidateCheckLicenceState(string licenceId)
        {
            if (licenceId == null)
                throw new ArgumentNullException(nameof(licenceId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="licenceId"></param>
        private void AfterCheckLicenceStateDefaultImplementation(ICheckLicenceStateApiResponse apiResponseLocalVar, string licenceId)
        {
            bool suppressDefaultLog = false;
            AfterCheckLicenceState(ref suppressDefaultLog, apiResponseLocalVar, licenceId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="licenceId"></param>
        partial void AfterCheckLicenceState(ref bool suppressDefaultLog, ICheckLicenceStateApiResponse apiResponseLocalVar, string licenceId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="licenceId"></param>
        private void OnErrorCheckLicenceStateDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string licenceId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCheckLicenceState(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, licenceId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="licenceId"></param>
        partial void OnErrorCheckLicenceState(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string licenceId);

        /// <summary>
        /// Verifica lo stato corrente di una licenza Restituisce lo stato della licenza identificata da licenceId: validita&#39;, data di scadenza, flag di pagamento. Puo&#39; essere usata anche come heartbeat del client (monitoraggio ogni 5 minuti).
        /// </summary>
        /// <param name="licenceId">Identificativo alfanumerico della licenza</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICheckLicenceStateApiResponse"/>&gt;</returns>
        public async Task<ICheckLicenceStateApiResponse?> CheckLicenceStateOrDefaultAsync(string licenceId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CheckLicenceStateAsync(licenceId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Verifica lo stato corrente di una licenza Restituisce lo stato della licenza identificata da licenceId: validita&#39;, data di scadenza, flag di pagamento. Puo&#39; essere usata anche come heartbeat del client (monitoraggio ogni 5 minuti).
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="licenceId">Identificativo alfanumerico della licenza</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICheckLicenceStateApiResponse"/>&gt;</returns>
        public async Task<ICheckLicenceStateApiResponse> CheckLicenceStateAsync(string licenceId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCheckLicenceState(licenceId);

                FormatCheckLicenceState(ref licenceId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/licence/state"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/licence/state");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["licenceId"] = ClientUtils.ParameterToString(licenceId);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<CheckLicenceStateApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<CheckLicenceStateApiResponse>();
                        CheckLicenceStateApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/licence/state", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCheckLicenceStateDefaultImplementation(apiResponseLocalVar, licenceId);

                        Events.ExecuteOnCheckLicenceState(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCheckLicenceStateDefaultImplementation(e, "/api/licence/state", uriBuilderLocalVar.Path, licenceId);
                Events.ExecuteOnErrorCheckLicenceState(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CheckLicenceStateApiResponse"/>
        /// </summary>
        public partial class CheckLicenceStateApiResponse : Org.OpenAPITools.Client.ApiResponse, ICheckLicenceStateApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<CheckLicenceStateApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="CheckLicenceStateApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CheckLicenceStateApiResponse(ILogger<CheckLicenceStateApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CheckLicenceStateApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CheckLicenceStateApiResponse(ILogger<CheckLicenceStateApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.LicenceStateResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.LicenceStateResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.LicenceStateResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.ErrorResponse? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out Org.OpenAPITools.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetNewLicence(GetNewLicenceRequest getNewLicenceRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="getNewLicenceRequest"></param>
        /// <returns></returns>
        private void ValidateGetNewLicence(GetNewLicenceRequest getNewLicenceRequest)
        {
            if (getNewLicenceRequest == null)
                throw new ArgumentNullException(nameof(getNewLicenceRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="getNewLicenceRequest"></param>
        private void AfterGetNewLicenceDefaultImplementation(IGetNewLicenceApiResponse apiResponseLocalVar, GetNewLicenceRequest getNewLicenceRequest)
        {
            bool suppressDefaultLog = false;
            AfterGetNewLicence(ref suppressDefaultLog, apiResponseLocalVar, getNewLicenceRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="getNewLicenceRequest"></param>
        partial void AfterGetNewLicence(ref bool suppressDefaultLog, IGetNewLicenceApiResponse apiResponseLocalVar, GetNewLicenceRequest getNewLicenceRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="getNewLicenceRequest"></param>
        private void OnErrorGetNewLicenceDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, GetNewLicenceRequest getNewLicenceRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetNewLicence(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, getNewLicenceRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="getNewLicenceRequest"></param>
        partial void OnErrorGetNewLicence(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, GetNewLicenceRequest getNewLicenceRequest);

        /// <summary>
        /// Rilascia una nuova licenza al cliente come file da scaricare Invocata dal client per ottenere una nuova licenza (p.es. dopo scadenza e pagamento avvenuto). Il server genera il file di licenza in locale e lo restituisce al client come download binario. I metadati della licenza (id, scadenza, pagato) vengono propagati tramite response header, mentre il body contiene il file stesso.
        /// </summary>
        /// <param name="getNewLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetNewLicenceApiResponse"/>&gt;</returns>
        public async Task<IGetNewLicenceApiResponse?> GetNewLicenceOrDefaultAsync(GetNewLicenceRequest getNewLicenceRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetNewLicenceAsync(getNewLicenceRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Rilascia una nuova licenza al cliente come file da scaricare Invocata dal client per ottenere una nuova licenza (p.es. dopo scadenza e pagamento avvenuto). Il server genera il file di licenza in locale e lo restituisce al client come download binario. I metadati della licenza (id, scadenza, pagato) vengono propagati tramite response header, mentre il body contiene il file stesso.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="getNewLicenceRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetNewLicenceApiResponse"/>&gt;</returns>
        public async Task<IGetNewLicenceApiResponse> GetNewLicenceAsync(GetNewLicenceRequest getNewLicenceRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetNewLicence(getNewLicenceRequest);

                FormatGetNewLicence(getNewLicenceRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/licence/new"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api/licence/new");

                    httpRequestMessageLocalVar.Content = (getNewLicenceRequest as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(getNewLicenceRequest, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/octet-stream",
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<GetNewLicenceApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetNewLicenceApiResponse>();
                        GetNewLicenceApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            case (200):
                            {
                                byte[] responseBytesArrayLocalVar = await httpResponseMessageLocalVar.Content.ReadAsByteArrayAsync(cancellationToken).ConfigureAwait(false);
                                System.IO.Stream responseContentStreamLocalVar = new System.IO.MemoryStream(responseBytesArrayLocalVar);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentStreamLocalVar, "/api/licence/new", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/licence/new", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetNewLicenceDefaultImplementation(apiResponseLocalVar, getNewLicenceRequest);

                        Events.ExecuteOnGetNewLicence(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetNewLicenceDefaultImplementation(e, "/api/licence/new", uriBuilderLocalVar.Path, getNewLicenceRequest);
                Events.ExecuteOnErrorGetNewLicence(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetNewLicenceApiResponse"/>
        /// </summary>
        public partial class GetNewLicenceApiResponse : Org.OpenAPITools.Client.ApiResponse, IGetNewLicenceApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetNewLicenceApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetNewLicenceApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetNewLicenceApiResponse(ILogger<GetNewLicenceApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetNewLicenceApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetNewLicenceApiResponse(ILogger<GetNewLicenceApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public System.IO.Stream? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? ContentStream
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out System.IO.Stream? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.ErrorResponse? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out Org.OpenAPITools.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 402 PaymentRequired
            /// </summary>
            /// <returns></returns>
            public bool IsPaymentRequired => 402 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 402 PaymentRequired
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.ErrorResponse? PaymentRequired()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsPaymentRequired
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 402 PaymentRequired and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryPaymentRequired([NotNullWhen(true)]out Org.OpenAPITools.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = PaymentRequired();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)402);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.ErrorResponse? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.ErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out Org.OpenAPITools.Model.ErrorResponse? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
