/*
 * Licence API
 *
 * API per la gestione delle licenze del client. Espone attivazione, rilascio di una nuova licenza e verifica dello stato corrente.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing LicenceApi
    /// </summary>
    public sealed class LicenceApiTests : ApiTestsBase
    {
        private readonly ILicenceApi _instance;

        public LicenceApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ILicenceApi>();
        }

        /// <summary>
        /// Test ActivateLicence
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ActivateLicenceAsyncTest()
        {
            ActivateLicenceRequest activateLicenceRequest = default!;
            var response = await _instance.ActivateLicenceAsync(activateLicenceRequest);
            var model = response.Ok();
            Assert.IsType<Licenza>(model);
        }

        /// <summary>
        /// Test CheckLicenceState
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CheckLicenceStateAsyncTest()
        {
            string licenceId = default!;
            var response = await _instance.CheckLicenceStateAsync(licenceId);
            var model = response.Ok();
            Assert.IsType<LicenceStateResponse>(model);
        }

        /// <summary>
        /// Test GetNewLicence
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetNewLicenceAsyncTest()
        {
            GetNewLicenceRequest getNewLicenceRequest = default!;
            var response = await _instance.GetNewLicenceAsync(getNewLicenceRequest);
            var model = response.Ok();
            Assert.IsType<System.IO.Stream>(model);
        }
    }
}
