// <auto-generated>
/*
 * Licence API
 *
 * API per la gestione delle licenze del client. Espone attivazione, rilascio di una nuova licenza e verifica dello stato corrente.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetNewLicenceRequest
    /// </summary>
    public partial class GetNewLicenceRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetNewLicenceRequest" /> class.
        /// </summary>
        /// <param name="clientId">Identificativo del cliente che richiede la nuova licenza</param>
        /// <param name="previousLicenceId">Identificativo della licenza precedente (opzionale, utile per tracciamento)</param>
        [JsonConstructor]
        public GetNewLicenceRequest(string clientId, Option<string?> previousLicenceId = default)
        {
            ClientId = clientId;
            PreviousLicenceIdOption = previousLicenceId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Identificativo del cliente che richiede la nuova licenza
        /// </summary>
        /// <value>Identificativo del cliente che richiede la nuova licenza</value>
        [JsonPropertyName("clientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// Used to track the state of PreviousLicenceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PreviousLicenceIdOption { get; private set; }

        /// <summary>
        /// Identificativo della licenza precedente (opzionale, utile per tracciamento)
        /// </summary>
        /// <value>Identificativo della licenza precedente (opzionale, utile per tracciamento)</value>
        [JsonPropertyName("previousLicenceId")]
        public string? PreviousLicenceId { get { return this.PreviousLicenceIdOption; } set { this.PreviousLicenceIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetNewLicenceRequest {\n");
            sb.Append("  ClientId: ").Append(ClientId).Append("\n");
            sb.Append("  PreviousLicenceId: ").Append(PreviousLicenceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetNewLicenceRequest" />
    /// </summary>
    public class GetNewLicenceRequestJsonConverter : JsonConverter<GetNewLicenceRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetNewLicenceRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetNewLicenceRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> clientId = default;
            Option<string?> previousLicenceId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "clientId":
                            clientId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "previousLicenceId":
                            previousLicenceId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!clientId.IsSet)
                throw new ArgumentException("Property is required for class GetNewLicenceRequest.", nameof(clientId));

            if (clientId.IsSet && clientId.Value == null)
                throw new ArgumentNullException(nameof(clientId), "Property is not nullable for class GetNewLicenceRequest.");

            if (previousLicenceId.IsSet && previousLicenceId.Value == null)
                throw new ArgumentNullException(nameof(previousLicenceId), "Property is not nullable for class GetNewLicenceRequest.");

            return new GetNewLicenceRequest(clientId.Value!, previousLicenceId);
        }

        /// <summary>
        /// Serializes a <see cref="GetNewLicenceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getNewLicenceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetNewLicenceRequest getNewLicenceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getNewLicenceRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetNewLicenceRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getNewLicenceRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetNewLicenceRequest getNewLicenceRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getNewLicenceRequest.ClientId == null)
                throw new ArgumentNullException(nameof(getNewLicenceRequest.ClientId), "Property is required for class GetNewLicenceRequest.");

            if (getNewLicenceRequest.PreviousLicenceIdOption.IsSet && getNewLicenceRequest.PreviousLicenceId == null)
                throw new ArgumentNullException(nameof(getNewLicenceRequest.PreviousLicenceId), "Property is required for class GetNewLicenceRequest.");

            writer.WriteString("clientId", getNewLicenceRequest.ClientId);

            if (getNewLicenceRequest.PreviousLicenceIdOption.IsSet)
                writer.WriteString("previousLicenceId", getNewLicenceRequest.PreviousLicenceId);
        }
    }
}
