// <auto-generated>
/*
 * Licence API
 *
 * API per la gestione delle licenze del client. Espone attivazione, rilascio di una nuova licenza e verifica dello stato corrente.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// LicenceStateResponse
    /// </summary>
    public partial class LicenceStateResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LicenceStateResponse" /> class.
        /// </summary>
        /// <param name="id">Identificativo alfanumerico della licenza</param>
        /// <param name="scadenza">Data/ora di scadenza</param>
        /// <param name="pagato">Licenza pagata</param>
        /// <param name="scaduta">True se la scadenza e&#39; gia&#39; passata al momento della risposta</param>
        /// <param name="serverTime">Istante del server al momento della verifica</param>
        [JsonConstructor]
        public LicenceStateResponse(string id, DateTime scadenza, bool pagato, bool scaduta, Option<DateTime?> serverTime = default)
        {
            Id = id;
            Scadenza = scadenza;
            Pagato = pagato;
            Scaduta = scaduta;
            ServerTimeOption = serverTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Identificativo alfanumerico della licenza
        /// </summary>
        /// <value>Identificativo alfanumerico della licenza</value>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Data/ora di scadenza
        /// </summary>
        /// <value>Data/ora di scadenza</value>
        [JsonPropertyName("scadenza")]
        public DateTime Scadenza { get; set; }

        /// <summary>
        /// Licenza pagata
        /// </summary>
        /// <value>Licenza pagata</value>
        [JsonPropertyName("pagato")]
        public bool Pagato { get; set; }

        /// <summary>
        /// True se la scadenza e&#39; gia&#39; passata al momento della risposta
        /// </summary>
        /// <value>True se la scadenza e&#39; gia&#39; passata al momento della risposta</value>
        [JsonPropertyName("scaduta")]
        public bool Scaduta { get; set; }

        /// <summary>
        /// Used to track the state of ServerTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ServerTimeOption { get; private set; }

        /// <summary>
        /// Istante del server al momento della verifica
        /// </summary>
        /// <value>Istante del server al momento della verifica</value>
        [JsonPropertyName("serverTime")]
        public DateTime? ServerTime { get { return this.ServerTimeOption; } set { this.ServerTimeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LicenceStateResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Scadenza: ").Append(Scadenza).Append("\n");
            sb.Append("  Pagato: ").Append(Pagato).Append("\n");
            sb.Append("  Scaduta: ").Append(Scaduta).Append("\n");
            sb.Append("  ServerTime: ").Append(ServerTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LicenceStateResponse" />
    /// </summary>
    public class LicenceStateResponseJsonConverter : JsonConverter<LicenceStateResponse>
    {
        /// <summary>
        /// The format to use to serialize Scadenza
        /// </summary>
        public static string ScadenzaFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ServerTime
        /// </summary>
        public static string ServerTimeFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="LicenceStateResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LicenceStateResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<DateTime?> scadenza = default;
            Option<bool?> pagato = default;
            Option<bool?> scaduta = default;
            Option<DateTime?> serverTime = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "scadenza":
                            scadenza = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "pagato":
                            pagato = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "scaduta":
                            scaduta = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "serverTime":
                            serverTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class LicenceStateResponse.", nameof(id));

            if (!scadenza.IsSet)
                throw new ArgumentException("Property is required for class LicenceStateResponse.", nameof(scadenza));

            if (!pagato.IsSet)
                throw new ArgumentException("Property is required for class LicenceStateResponse.", nameof(pagato));

            if (!scaduta.IsSet)
                throw new ArgumentException("Property is required for class LicenceStateResponse.", nameof(scaduta));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class LicenceStateResponse.");

            if (scadenza.IsSet && scadenza.Value == null)
                throw new ArgumentNullException(nameof(scadenza), "Property is not nullable for class LicenceStateResponse.");

            if (pagato.IsSet && pagato.Value == null)
                throw new ArgumentNullException(nameof(pagato), "Property is not nullable for class LicenceStateResponse.");

            if (scaduta.IsSet && scaduta.Value == null)
                throw new ArgumentNullException(nameof(scaduta), "Property is not nullable for class LicenceStateResponse.");

            if (serverTime.IsSet && serverTime.Value == null)
                throw new ArgumentNullException(nameof(serverTime), "Property is not nullable for class LicenceStateResponse.");

            return new LicenceStateResponse(id.Value!, scadenza.Value!.Value!, pagato.Value!.Value!, scaduta.Value!.Value!, serverTime);
        }

        /// <summary>
        /// Serializes a <see cref="LicenceStateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="licenceStateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LicenceStateResponse licenceStateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, licenceStateResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LicenceStateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="licenceStateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LicenceStateResponse licenceStateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (licenceStateResponse.Id == null)
                throw new ArgumentNullException(nameof(licenceStateResponse.Id), "Property is required for class LicenceStateResponse.");

            writer.WriteString("id", licenceStateResponse.Id);

            writer.WriteString("scadenza", licenceStateResponse.Scadenza.ToString(ScadenzaFormat));

            writer.WriteBoolean("pagato", licenceStateResponse.Pagato);

            writer.WriteBoolean("scaduta", licenceStateResponse.Scaduta);

            if (licenceStateResponse.ServerTimeOption.IsSet)
                writer.WriteString("serverTime", licenceStateResponse.ServerTimeOption.Value!.Value.ToString(ServerTimeFormat));
        }
    }
}
